name: Checkout, Setup NodeJS and Install dependencies
description: A composite action to checkout, setup NodeJS and install dependencies

branding:
  icon: arrow-down-circle
  color: purple

inputs:
  node-version:
    description: NodeJS version to setup
    required: false
    default: 20.x

  registry-url:
    description: Registry URL
    required: false
    default: https://registry.npmjs.org/

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NodeJS ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash
