name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  create_release:
    name: Release Action to GitHub

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true

  extract_major_version:
    name: Extract Major Version

    runs-on: ubuntu-latest
    needs: create_release

    outputs:
      major-tag: ${{ steps.extract-tag.outputs.tag }}

    steps:
      - name: setup NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Extract Major Tag
        id: extract-tag
        run: echo "tag=$(node ${{ github.action_path }}/scripts/extract-major-tag.js ${{ github.ref_name }})" >> $GITHUB_OUTPUT

  update_major:
    name: Update Major version

    runs-on: ubuntu-latest
    needs: extract_major_version

    steps:
      - run: |
          echo "Just show major tag for now"
          echo "major-tag = ${{ needs.extract_major_version.outputs.major-tag }}"
