name: Create Release
run-name: Create Release for ${{ github.ref_name }}

on:
  push:
    tags:
      - v*.*.*

jobs:
  create_release:
    name: Release Action to GitHub

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true

      - name: Show Release URL on summary
        run: echo "GitHub Release Created! ( ${{ steps.create-release.outputs.url }} )" >> $GITHUB_STEP_SUMMARY
